import Link from 'next/link';
import { codeToHtml } from 'shiki';
import { assumptions } from '../../engine/assumptions';
import { modelSnippets,pipelineSnippet } from '../../content/modelSnippets';
export default async function ModelPage(){
  const pipelineHtml=await codeToHtml(pipelineSnippet,{lang:'python',theme:'github-light'});
  const cards=await Promise.all(modelSnippets.map(async s=>({...s,html:await codeToHtml(s.code,{lang:'python',theme:'github-light'})})));
  const groups=[...new Set(assumptions.map(a=>a.group))];
  return <main className="model-shell"><aside className="model-toc"><div className="eyebrow">MODEL REFERENCE</div><a href="#pipeline">Pipeline</a><a href="#functions">Functions</a>{groups.map(g=><a key={g} href={`#${g.toLowerCase().replace(/[^a-z]+/g,'-')}`}>{g}</a>)}</aside><div className="model-content"><div className="model-intro"><div className="eyebrow">METHOD / TRACEABILITY</div><h1>Model & assumptions</h1><p>Simplified Python-style examples of each block. The live simulator runs an equivalent TypeScript engine.</p><Link href="/" className="back-link">← Back to simulator</Link></div><section id="pipeline" className="model-section"><div className="eyebrow">01 / PIPELINE</div><h2>One run, from inputs to margins</h2><p>The simulation follows the system-flow diagram. All signals share one time grid.</p><div className="code-wrap" dangerouslySetInnerHTML={{__html:pipelineHtml}}/></section><section id="functions" className="model-section"><div className="eyebrow">02 / FUNCTIONS</div><h2>Calculation blocks</h2><div className="function-list">{cards.map(s=><article className="function-card" key={s.order}><div className="function-top"><span className="function-number">{String(s.order).padStart(2,'0')}</span><span className="block-tag">{s.block}</span><code>{s.file}</code></div><h3>{s.name.replaceAll('_',' ')}</h3><p>{s.summary}</p>{s.formula&&<div className="formula">{s.formula}</div>}<div className="code-wrap" dangerouslySetInnerHTML={{__html:s.html}}/><small>Mirrors TypeScript: <code>{s.mirrors}</code></small></article>)}</div></section><section className="model-section"><div className="eyebrow">03 / ASSUMPTIONS</div><h2>What the model assumes</h2><p>“Placeholder” values are useful for demonstration and should be replaced with spacecraft or flight data for engineering use.</p>{groups.map(group=><div className="assumption-group" key={group} id={group.toLowerCase().replace(/[^a-z]+/g,'-')}><h3>{group}</h3>{assumptions.filter(a=>a.group===group).map(a=><div className="assumption" key={a.id}><span className={`origin ${a.origin}`}>{a.origin.replace('-',' ')}</span><div><p>{a.text}</p>{a.params&&<small>Controls: {a.params.join(' · ')}</small>}</div></div>)}</div>)}</section></div></main>;
}
