export interface Assumption { id:string;group:'Orbit'|'Eclipse & sun'|'Magnetic field & ground'|'Power gain'|'Power used'|'Battery & rules'|'Design loops & numerics';text:string;origin:'user-note'|'simplification'|'placeholder'|'standard';params?:string[]; }
export const assumptions:Assumption[]=[
{id:'orbit-circle',group:'Orbit',text:'Circular orbits only. Period T = 2π√(r³/μ).',origin:'user-note',params:['orbit.altitudeKm']},
{id:'orbit-two-body',group:'Orbit',text:'Two-body motion; no J2, drift or manoeuvres. The ascending node is fixed at 0°.',origin:'simplification'},
{id:'beta-fixed',group:'Orbit',text:'Beta is set directly and held constant. It is not tied to a calendar date; some beta and inclination combinations may be unreachable.',origin:'simplification',params:['orbit.betaDeg','orbit.inclinationDeg']},
{id:'eclipse-beta',group:'Eclipse & sun',text:'An eclipse occurs only when |β| < asin(R_E/r); beta also sets its duration.',origin:'user-note',params:['orbit.betaDeg']},
{id:'eclipse-cyl',group:'Eclipse & sun',text:'Earth casts a cylindrical shadow. Penumbra and lunar eclipses are excluded.',origin:'simplification'},
{id:'solar-flux',group:'Eclipse & sun',text:'Solar flux is 1361 W/m² on average, 1322 at aphelion, or 1414 at perihelion. Other solar variability, albedo and IR are excluded.',origin:'user-note',params:['environment.fluxCase']},
{id:'field',group:'Magnetic field & ground',text:'A centred, aligned quiet-time dipole approximates the field. The field scale stands in for storm and model uncertainty.',origin:'simplification',params:['environment.fieldScale']},
{id:'stations',group:'Magnetic field & ground',text:'Ground stations are fixed on rotating Earth. Earth phase at t = 0 is arbitrary; contact requires elevation above the mask.',origin:'simplification',params:['environment.elevationMaskDeg']},
{id:'eta',group:'Power gain',text:'Array efficiency combines cell conversion, BOL to EOL degradation, and regulator/harness path efficiency.',origin:'user-note',params:['gain.etaCell','gain.eolFactor','gain.etaPath']},
{id:'array-zero',group:'Power gain',text:'Solar output is zero in eclipse; self-shadowing and temperature effects beyond the efficiency factor are excluded.',origin:'simplification'},
{id:'payload',group:'Power used',text:'Payload power depends strongly on satellite type. Preset powers and duty schedules are illustrative placeholders.',origin:'placeholder',params:['used.payload.profile','used.payload.onW']},
{id:'adcs-thermal',group:'Power used',text:'ADCS is mostly on. Thermal heaters draw more power in eclipse.',origin:'simplification',params:['used.adcs.duty','used.thermal.eclipseW']},
{id:'comms',group:'Power used',text:'Comms is satellite to ground only. Transmit power occurs during contact windows; there are no crosslinks.',origin:'user-note',params:['used.comms.txW']},
{id:'torquer',group:'Power used',text:'The torquer only dumps momentum. SRP is the only disturbance. Available torque is k_eff·m·|B| and duty is t_on/T.',origin:'simplification',params:['used.torquer.dipoleAm2','used.torquer.kEff']},
{id:'cooler',group:'Power used',text:'Always-on and on-demand pre-cooling are compared per orbit. Power is constant per mode; no radiator-temperature effect.',origin:'user-note',params:['used.cooler.mode']},
{id:'z01',group:'Power used',text:'The 3,500 A·m² dipole is a public Z01 figure. The cooler and driver split is a placeholder; use flight data before design decisions.',origin:'placeholder',params:['used.torquer.dipoleAm2','used.cooler.steadyW']},
{id:'battery',group:'Battery & rules',text:'One lumped battery has constant charge/discharge efficiency and a charge-rate cap; surplus is shunted. Temperature and ageing effects are excluded.',origin:'simplification',params:['battery.capacityWh']},
{id:'dod',group:'Battery & rules',text:'DoD is one minus the minimum SoC over the last orbit; the model runs multiple orbits to check the trend.',origin:'user-note',params:['sim.nOrbits','battery.dodLimit']},
{id:'shedding',group:'Battery & rules',text:'Optional load shedding applies below a threshold with hysteresis: payload drops to standby, then comms switches off.',origin:'user-note',params:['rules.loadShedding','rules.shedThreshold']},
{id:'sizing',group:'Design loops & numerics',text:'Sizing uses beta 0°, aphelion, EOL and the storm field scale, with array and battery bisection.',origin:'simplification',params:['design.marginTarget']},
{id:'numerics',group:'Design loops & numerics',text:'Fixed time steps and double-precision numbers are used. Analyses use a coarser time step.',origin:'standard',params:['sim.dt','sim.analysisDt']},
];
