import { z } from 'zod';
type FieldMeta = { label:string; unit?:string; step?:number; softMin?:number; softMax?:number; group:string; control?:'slider'|'toggle'|'select'; help?:string; advanced?:boolean; showIf?:string; options?:string[]; placeholder?:boolean };
const num=(d:number,min:number,max:number,m:FieldMeta)=>z.number().min(min).max(max).default(d).meta({...m,control:'slider',min,max});
const bool=(d:boolean,m:FieldMeta)=>z.boolean().default(d).meta({...m,control:'toggle'});
const sel=<T extends readonly [string,...string[]]>(options:T,d:T[number],m:FieldMeta)=>z.enum(options).default(d).meta({...m,control:'select',options:[...options]});
const g=(group:string,label:string,extra:Partial<FieldMeta>={})=>({group,label,...extra});
export const ScenarioConfigSchema=z.object({
  sim:z.object({case:sel(['BOL','EOL'],'EOL',g('Scenario','Life case')),worstCase:bool(true,g('Scenario','Worst case')),nOrbits:num(3,1,10,g('Scenario','Orbits',{step:1,softMin:1,softMax:6})),dt:num(30,10,120,g('Scenario','Time step',{unit:'s',step:10,softMin:10,softMax:120})),analysisDt:num(120,30,600,g('Scenario','Analysis step',{unit:'s',step:30,advanced:true}))}),
  orbit:z.object({altitudeKm:num(20200,2000,35786,g('Orbit','Altitude',{unit:'km',step:10,softMin:2000,softMax:35786})),inclinationDeg:num(55,0,90,g('Orbit','Inclination',{unit:'°',step:1,softMin:0,softMax:90})),betaDeg:num(0,-90,90,g('Orbit','Beta angle',{unit:'°',step:1,softMin:-90,softMax:90,help:'Sun angle above the orbit plane; fixed during each run.'}))}),
  environment:z.object({fluxCase:sel(['mean','aphelion','perihelion'],'mean',g('Environment','Solar flux')),fieldScale:num(1,0.5,1.5,g('Environment','Field scale',{step:0.05,softMin:0.5,softMax:1.5})),stormScale:num(0.7,0.5,1.5,g('Environment','Worst-case field scale',{step:0.05,advanced:true})),awaruEnabled:bool(true,g('Environment','Awarua station')),svalbardEnabled:bool(true,g('Environment','Svalbard station')),elevationMaskDeg:num(10,0,45,g('Environment','Elevation mask',{unit:'°',step:1}))}),
  gain:z.object({area:num(1.4,0.1,50,g('Power gain','Array area',{unit:'m²',step:0.1,softMin:0.1,softMax:12,placeholder:true})),etaCell:num(0.3,0.05,0.45,g('Power gain','Cell efficiency',{step:0.01,softMin:0.1,softMax:0.4})),eolFactor:num(0.85,0.5,1,g('Power gain','EOL factor',{step:0.01,placeholder:true})),etaPath:num(0.9,0.5,1,g('Power gain','Path efficiency',{step:0.01})),tracking:sel(['twoAxis','oneAxis','fixed'],'twoAxis',g('Power gain','Array tracking')),fixedAngleDeg:num(30,0,90,g('Power gain','Fixed angle',{unit:'°',step:1,showIf:'gain.tracking=fixed'}))}),
  used:z.object({
    payload:z.object({enabled:bool(true,g('Power used','Payload enabled')),profile:sel(['navigation','relay','science','custom'],'navigation',g('Power used','Payload type',{placeholder:true})),schedule:sel(['continuous','sunlitOnly','evenlySpread'],'continuous',g('Power used','Payload schedule')),onW:num(200,0,10000,g('Power used','Payload active',{unit:'W',step:10,softMax:1500,placeholder:true})),standbyW:num(20,0,1000,g('Power used','Payload standby',{unit:'W',step:5,softMax:150,placeholder:true})),duty:num(1,0,1,g('Power used','Payload duty',{step:0.05}))}),
    adcs:z.object({enabled:bool(true,g('Power used','ADCS enabled')),powerW:num(35,0,1000,g('Power used','ADCS power',{unit:'W',step:5,softMax:150,placeholder:true})),duty:num(1,0,1,g('Power used','ADCS duty',{step:0.05}))}),
    comms:z.object({enabled:bool(true,g('Power used','Comms enabled')),txW:num(60,0,2000,g('Power used','Comms transmit',{unit:'W',step:5,softMax:200,placeholder:true})),standbyW:num(8,0,500,g('Power used','Comms standby',{unit:'W',step:1,softMax:50,placeholder:true}))}),
    thermal:z.object({enabled:bool(true,g('Power used','Thermal enabled')),eclipseW:num(40,0,2000,g('Power used','Eclipse heater',{unit:'W',step:5,softMax:250,placeholder:true})),sunW:num(5,0,500,g('Power used','Sunlight heater',{unit:'W',step:1,softMax:50,placeholder:true}))}),
    torquer:z.object({enabled:bool(true,g('Power used','Torquer enabled')),dipoleAm2:num(3500,0,10000,g('Power used','Torquer dipole',{unit:'A·m²',step:100,softMax:6000})),driverW:num(5,0,200,g('Power used','Driver power',{unit:'W',step:1,softMax:50,placeholder:true})),kEff:num(0.6,0,1,g('Power used','Torque geometry factor',{step:0.05,placeholder:true})),srpAreaM2:num(6,0,1000,g('Power used','SRP area',{unit:'m²',step:1,softMax:50,placeholder:true})),reflectivity:num(0.6,0,1,g('Power used','Reflectivity',{step:0.05,placeholder:true})),cpOffsetM:num(0.15,0,10,g('Power used','Pressure offset',{unit:'m',step:0.01,softMax:1,placeholder:true})),dHManual:num(0,0,10,g('Power used','Momentum override',{unit:'N·m·s',step:0.001,softMax:0.05,advanced:true,help:'Zero uses SRP calculation.'}))}),
    cooler:z.object({enabled:bool(true,g('Power used','Cryocooler enabled')),mode:sel(['alwaysOn','onDemand','auto'],'alwaysOn',g('Power used','Cooler mode')),steadyW:num(20,0,500,g('Power used','Cooler steady',{unit:'W',step:1,softMax:100,placeholder:true})),cooldownW:num(42,0,1000,g('Power used','Cool-down power',{unit:'W',step:1,softMax:150,placeholder:true})),idleW:num(0,0,100,g('Power used','Cooler idle',{unit:'W',step:1,softMax:20,placeholder:true})),precoolMin:num(30,0,240,g('Power used','Pre-cool duration',{unit:'min',step:5,softMax:120,placeholder:true})),offInEclipse:bool(false,g('Power used','Cooler off in eclipse',{showIf:'used.cooler.mode=alwaysOn'}))})
  }),
  battery:z.object({capacityWh:num(600,10,50000,g('Battery','Capacity',{unit:'Wh',step:50,softMax:6000,placeholder:true})),soc0:num(1,0,1,g('Battery','Initial SoC',{step:0.05})),etaCharge:num(0.95,0.5,1,g('Battery','Charge efficiency',{step:0.01})),etaDischarge:num(0.95,0.5,1,g('Battery','Discharge efficiency',{step:0.01})),maxChargeC:num(0.5,0.01,5,g('Battery','Max charge rate',{unit:'C',step:0.05,softMax:2})),dodLimit:num(0.6,0.05,1,g('Battery','DoD limit',{step:0.05}))}),
  rules:z.object({loadShedding:bool(false,g('Rules','Load shedding')),shedThreshold:num(0.3,0,0.9,g('Rules','Shed threshold',{step:0.05,showIf:'rules.loadShedding=true'})),shedHysteresis:num(0.1,0.01,0.5,g('Rules','Restore hysteresis',{step:0.01,showIf:'rules.loadShedding=true'})),dumpInSunlightOnly:bool(true,g('Rules','Dump in sunlight only'))}),
  design:z.object({marginTarget:num(0.2,0,1,g('Design loops','Energy margin target',{step:0.05})),arrayMin:num(0.1,0.1,20,g('Design loops','Minimum array area',{unit:'m²',step:0.1,advanced:true})),arrayMax:num(50,1,100,g('Design loops','Maximum array area',{unit:'m²',step:1,advanced:true}))})
});
export type ScenarioConfig=z.infer<typeof ScenarioConfigSchema>;
export type Preset='smallMeo'|'gnssClass';
export function defaultConfig(preset:Preset='smallMeo'):ScenarioConfig { const c=ScenarioConfigSchema.parse({sim:{},orbit:{},environment:{},gain:{},used:{payload:{},adcs:{},comms:{},thermal:{},torquer:{},cooler:{}},battery:{},rules:{},design:{}}); if(preset==='gnssClass'){c.orbit.altitudeKm=23222;c.orbit.inclinationDeg=56;c.gain.area=7;c.gain.eolFactor=0.8;c.used.payload.onW=1200;c.used.payload.standbyW=100;c.used.adcs.powerW=80;c.used.comms.txW=80;c.used.comms.standbyW=15;c.used.thermal.eclipseW=150;c.used.thermal.sunW=20;c.used.torquer.srpAreaM2=25;c.used.torquer.cpOffsetM=0.3;c.battery.capacityWh=3000;} return c; }
export function applyCase(input:ScenarioConfig):ScenarioConfig { const c=structuredClone(input); if(c.sim.worstCase){c.orbit.betaDeg=0;c.environment.fluxCase='aphelion';c.sim.case='EOL';c.environment.fieldScale=c.environment.stormScale;} return c; }
